# -*- coding: utf-8 -*-
#
# This file is part of pytest-invenio.
# Copyright (C) 2017-2018 CERN.
#
# pytest-invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome
  apt:
    packages:
      - xvfb
      - chromium-chromedriver

notifications:
  email: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel

cache:
  - pip

services:
  - xvfb

env:
  global:
    - E2E_OUTPUT=base64
    - ES_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.2.tar.gz
  matrix:
    - REQUIREMENTS=lowest
    - REQUIREMENTS=release DEPLOY=true
    - REQUIREMENTS=devel

python:
  - "3.6"
  - "3.7"

before_install:
  # Download and start ES
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  # Chrome webdriver for Selenium
  - "PATH=$PATH:$HOME/webdrivers"
  - "if [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi"
  # Install packages
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"
  # Uninstall numpy (present by default in Travis/Python workers)
  # as it causes side effects with elasticsearch-py
  - pip uninstall numpy -y
  - pip freeze

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "UES49TwCHOmAsSx/cuUfzWa8nrUuTtXHz/RCgz2gx1svZWavfRyNwr4E/9u9iyETUcN1n1qPwq32dFlm+nBCHI6uAHgIeVJConaNqYxp8/fAsZfLwD9CBe/K4V7nGUxeHjgkJmg3mPAkVAwHSusRZtcyvIx1CMrVc5WPh8E7H0XlHB7lw7CZ0CrShccq+uw1EwP8yXfOJrWjfY5NfIz7avNxbk0Rmxnj/ucqxI4GE6Ex19ra7w9RlQkfu7s17Ma/QYMI5JdZ29FQfUV1TV4ZHymaH+Vql85BMYxEk83pQKVx65pcoAZt28LrrzPs0kmLNVtWJbmjud26YBeLrAK3Ks2GsuNqMQFjcO1yUEdsHKbQ8cQE9n9Ifo0xYRwjx1C3kfIqUtBmeYY1M8n5sobpHECizhFtDmSFuO+Y0zSgvGgAW831jvWmIZHfspKI0Xek3KGikcvtZR4dL8WAmdF7jFrjx4cDzzhbSFO+4mHEP6DT+L7LGhxL8XnDSMjekrP3w0sPstbCL5iKcboiqi1xOud7Lxvme0mDrVze+D5kIO7V3it3coZ3Pe5LI36p9rzYSPJfRCy8tMRie8BEQP3sqOdyadWJnywJIxhSJp0SD7l2vtP9uLWuW7+97JWaGGdEHLeQHpu1x8pNf0CTEtWTKnlAykM5z6/wyPnUkBMm/Kk="
  distributions: sdist bdist_wheel
  on:
    condition: $DEPLOY = true
    python: '3.6'
    repo: inveniosoftware/pytest-invenio
    tags: true
